import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,verify} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createLicenseService,addMonths} from '../billing/license-service.mjs';
import {licenseAccess} from '../lib/license-access.ts';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}),device='A'.repeat(64);
function harness(database=':memory:'){let now=Date.UTC(2026,0,1)/1000;const calls=[];const service=createLicenseService({database,privateKey,now:()=>now,provider:{async createCheckout(order){calls.push(order);return {id:'provider-'+order.orderId,url:'https://payments.example.test/'+order.orderId};}}});return {service,calls,time:value=>now=value,payment:o=>({orderId:o.id,providerOrder:'provider-'+o.id,id:'paid-'+o.id,status:'paid',amountMinor:o.amountMinor,currency:'AZN'})};}
test('quote is 10 AZN per whole month; invalid periods never create a payment',async()=>{const h=harness();try{const order=await h.service.checkout(3);assert.equal(order.amountMinor,3000);assert.equal(h.calls[0].currency,'AZN');for(const months of [0,-1,1.5,121,'3'])await assert.rejects(h.service.checkout(months));assert.equal(h.calls.length,1);}finally{h.service.close();}});
test('no provider means no live checkout',async()=>{const s=createLicenseService({database:':memory:',privateKey});try{assert.equal(s.catalog().enabled,false);await assert.rejects(s.checkout(3),/qoşulmayıb/);}finally{s.close();}});
test('unpaid order and invalid webhook never issue activation',async()=>{const h=harness();try{const o=await h.service.checkout(3);assert.equal(h.service.status(o.id,o.token).activationCode,undefined);for(const changed of [{amountMinor:1},{currency:'USD'},{status:'pending'},{providerOrder:'other'}])assert.throws(()=>h.service.confirmPayment({...h.payment(o),...changed}));assert.equal(h.service.status(o.id,o.token).status,'pending');assert.throws(()=>h.service.activate('RADAZ-ACT-'+'A'.repeat(48),device));assert.throws(()=>h.service.status(o.id,'invalid'));}finally{h.service.close();}});
test('payment does not start time; first activation starts selected calendar months',async()=>{const h=harness();try{const o=await h.service.checkout(3);h.service.confirmPayment(h.payment(o));const paid=h.service.status(o.id,o.token);assert.equal(paid.activatedAt,null);h.time(Date.UTC(2026,4,31,10)/1000);const receipt=h.service.activate(paid.activationCode,device);assert.equal(receipt.activatedAt,Date.UTC(2026,4,31,10)/1000);assert.equal(receipt.expiresAt,Date.UTC(2026,7,31,10)/1000);const [prefix,payload,signature]=receipt.key.split('.');assert.ok(verify('RSA-SHA256',Buffer.from(prefix+'.'+payload),publicKey,Buffer.from(signature,'base64url')));assert.equal(JSON.parse(Buffer.from(payload,'base64url')).months,3);}finally{h.service.close();}});
test('month-end activation handles February and leap years',()=>{assert.equal(addMonths(Date.UTC(2026,0,31)/1000,1),Date.UTC(2026,1,28)/1000);assert.equal(addMonths(Date.UTC(2028,0,31)/1000,1),Date.UTC(2028,1,29)/1000);});
test('duplicate payment and reactivation cannot extend expired license',async()=>{const h=harness();try{const o=await h.service.checkout(1);h.service.confirmPayment(h.payment(o));const paid=h.service.status(o.id,o.token),first=h.service.activate(paid.activationCode,device);h.service.confirmPayment(h.payment(o));assert.equal(h.service.status(o.id,o.token).activationCode,paid.activationCode);h.time(first.expiresAt+86400);assert.equal(h.service.activate(paid.activationCode,device).expiresAt,first.expiresAt);assert.throws(()=>h.service.activate(paid.activationCode,'B'.repeat(64)),/başqa kompüter/);}finally{h.service.close();}});
test('one provider payment cannot pay another order',async()=>{const h=harness();try{const a=await h.service.checkout(1),b=await h.service.checkout(1);h.service.confirmPayment(h.payment(a));assert.throws(()=>h.service.confirmPayment({...h.payment(b),id:h.payment(a).id}));assert.equal(h.service.status(b.id,b.token).status,'pending');}finally{h.service.close();}});
test('server restart preserves first activation and device binding',async()=>{const folder=mkdtempSync(path.join(os.tmpdir(),'radaz-billing-'));let h=harness(path.join(folder,'test.sqlite'));try{const o=await h.service.checkout(12);h.service.confirmPayment(h.payment(o));const code=h.service.status(o.id,o.token).activationCode;const first=h.service.activate(code,device);h.service.close();h=harness(path.join(folder,'test.sqlite'));h.time(first.expiresAt+86400);assert.equal(h.service.activate(code,device).expiresAt,first.expiresAt);assert.throws(()=>h.service.activate(code,'B'.repeat(64)));}finally{h.service.close();assert.ok(path.resolve(folder).startsWith(path.resolve(os.tmpdir())+path.sep+'radaz-billing-'));rmSync(folder,{recursive:true,force:true});}});
test('expired license preserves PACS/archive/CD and list-only Viewer; advanced routes blocked',()=>{for(const route of ['/','/archive','/pacs','/media'])assert.deepEqual(licenseAccess(true,false,route),{limited:true,blocked:false});for(const route of ['/report','/3d','/mpr','/print','/printer-settings'])assert.equal(licenseAccess(true,false,route).blocked,true);assert.equal(licenseAccess(true,true,'/report').limited,false);assert.equal(licenseAccess(false,false,'/report').blocked,false);});
