import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import JSZip from 'jszip';
import {chatgptPrompt} from '../lib/chatgpt-prompt.ts';
const context={JSZip,File,Uint8Array};vm.createContext(context);vm.runInContext(readFileSync(new URL('../extensions/chatgpt/composer-helpers.js',import.meta.url),'utf8'),context);
async function source(total=25){const zip=new JSZip(),images=[];for(let i=1;i<=total;i++){const name=`RADAZ-image-${String(i).padStart(6,'0')}.jpg`;images.push({name,series:1,slice:i});zip.file(name,Buffer.from([255,216,255,217]));}zip.file('manifest.json',JSON.stringify({imageCount:total,images}));return zip;}
test('single CR is attached as a real JPEG and the complete ZIP',async()=>{const raw=await(await source(1)).generateAsync({type:'uint8array'});const files=await context.RADAZChatGPT.files([raw],{name:'RADAZ-ChatGPT.zip',attachments:{first:0,count:1,total:1,includeZip:true}});assert.deepEqual(Array.from(files,f=>[f.name,f.type]),[['RADAZ-image-000001.jpg','image/jpeg'],['RADAZ-ChatGPT.zip','application/zip']]);assert.deepEqual(new Uint8Array(await files[0].arrayBuffer()),new Uint8Array([255,216,255,217]));});
test('explicit last JPEG group covers all remaining images without a phantom ZIP',async()=>{const raw=await(await source()).generateAsync({type:'uint8array'});const files=await context.RADAZChatGPT.files([raw],{name:'RADAZ-ChatGPT.zip',attachments:{first:24,count:1,total:25,includeZip:false}});assert.equal(files.length,1);assert.equal(files[0].name,'RADAZ-image-000025.jpg');});
test('reject missing JPEG and mismatched manifest rather than skipping images',async()=>{const zip=await source(2);zip.remove('RADAZ-image-000002.jpg');let raw=await zip.generateAsync({type:'uint8array'});await assert.rejects(context.RADAZChatGPT.files([raw],{name:'RADAZ-ChatGPT.zip',attachments:{first:0,count:2,total:2,includeZip:true}}),/tapılmadı/);raw=await(await source(1)).generateAsync({type:'uint8array'});await assert.rejects(context.RADAZChatGPT.files([raw],{name:'RADAZ-ChatGPT.zip',attachments:{first:0,count:1,total:2,includeZip:false}}),/sayı uyğun/);});
test('ZIP-only transfer attaches one archive and prompt requests every image in manifest order',async()=>{const raw=await(await source(25)).generateAsync({type:'uint8array'});const files=await context.RADAZChatGPT.files([raw],{name:'RADAZ-ChatGPT.zip'});assert.equal(files.length,1);assert.equal(files[0].type,'application/zip');assert.deepEqual(new Uint8Array(await files[0].arrayBuffer()),raw);const prompt=chatgptPrompt({imageCount:25,seriesCount:1,modality:'CR',windowMode:'metadata',clinical:''});assert.match(prompt,/Dərindən, tək-tək analiz et və rapor yaz/);assert.match(prompt,/ZIP-də 25 JPEG/);assert.match(prompt,/manifest.json sırasına/);assert.doesNotMatch(prompt,/Birbaşa görüntü əlavələri|ZIP yoxdur/);assert.match(prompt,/görüntüsüz radioloji hesabat bölmələri yaratma/);});
