const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
const form=document.querySelector('form'),status=document.querySelector('#status');
const field=name=>form.elements.namedItem(name);
const urls=()=>{const base=field('publicBaseUrl').value.trim().replace(/\/$/,'');document.querySelector('#callback').textContent=base?base+'/v1/webhooks/provider':'Əvvəl HTTPS domenini daxil edin.';document.querySelector('#return').textContent=base?base+'/payment/return':'—';};
async function request(body){const response=await fetch('/settings',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error);return data;}
function populate(data){for(const [name,value]of Object.entries(data)){const input=field(name);if(!input)continue;if(input.type==='checkbox')input.checked=!!value;else input.value=value;}field('epointPrivateKey').value='';field('clearPrivateKey').checked=false;document.querySelector('#secret-state').textContent=data.privateKeyConfigured?'Gizli açar saxlanıb; burada geri göstərilmir.':'Gizli açar hələ daxil edilməyib.';urls();}
field('publicBaseUrl').addEventListener('input',urls);
request().then(data=>{populate(data);document.querySelector('#storage').textContent=data.storagePath;document.querySelector('#save').disabled=false;}).catch(error=>status.textContent=error.message);
form.addEventListener('submit',async event=>{event.preventDefault();document.querySelector('#save').disabled=true;try{const body=Object.fromEntries(new FormData(form));body.enabled=field('enabled').checked;body.clearPrivateKey=field('clearPrivateKey').checked;populate(await request(body));status.textContent='Ayarlar saxlandı. Ödəniş serverini yenidən başladın. Bank kabinetində rekvizitlərin ayrıca təsdiqləndiyini yoxlayın.';}catch(error){status.textContent=error.message;}finally{document.querySelector('#save').disabled=false;}});
