import {RadazLogo} from '@/components/radaz-logo';
import {AppHelpMenu} from '@/components/app-product';
export default function ChatGPTHelp(){return <main className="chatgpt-help-page"><header><RadazLogo size={55}/><div><small>RADAZ</small><h1>ChatGPT-yə görüntü ötürmə</h1></div><AppHelpMenu/></header>
<p>API açarı tələb olunmur. 0.3.2 əlavəsi JPEG-ləri birbaşa görüntü kimi, bütün seçilmiş görüntüləri isə əlavə ZIP kimi ChatGPT mesaj sahəsinə yerləşdirir. Mesajı özünüz göndərirsiniz.</p>
<ol><li><a href="/radaz-chatgpt-extension.zip" download>RADAZ ChatGPT əlavəsini 0.3.2 yükləyin</a> və ZIP-i ayrıca qovluğa çıxarın.</li><li>Chrome-da <code>chrome://extensions</code> və ya Edge-də <code>edge://extensions</code> açın. Developer mode → Load unpacked ilə çıxarılmış qovluğu seçin. Əvvəlki əlavə varsa, yeni faylları onun qovluğuna çıxarıb Reload basın.</li><li>Əlavənin ayarlarında istifadə etdiyiniz RADAZ ünvanını qeyd edin, məsələn <code>http://localhost:5173</code> və ya LAN ünvanı. RADAZ səhifəsini yeniləyin.</li><li>ChatGPT hesabınıza daxil olun. RADAZ → Hesabat səhifəsində ZIP hazırlayın və JPEG önbaxışlarını yoxlayın.</li><li>“Görüntüləri ChatGPT-yə ötür” düyməsini basın. 8-dən çox görüntü varsa, birbaşa JPEG qrupunu seçin; bütün görüntülər yenə ZIP-də qalır. Sonrakı JPEG qrupları ayrıca ötürülür və tam müayinə kimi təqdim edilmir.</li><li>ChatGPT-də JPEG əlavələrinin və ZIP-in yüklənməsi təsdiqləndikdən sonra tapşırıq yerləşdirilir. Görüntü önbaxışlarını yoxlayıb mesajı göndərin. ZIP qəbul edilmirsə, RADAZ-da “ZIP-i də əlavə et” seçimini söndürüb yalnız JPEG-ləri ötürün.</li><li>Cavab hazır olduqda “RADAZ-a qaytar” düyməsini basın. Analiz hesabat səhifəsində görünəcək. Yoxlayıb hesabata əlavə edin.</li></ol>
<h2>“Görüntü əlçatan deyil” cavabı gəlirsə</h2><p>Həmin cavab görüntü analizi deyil. RADAZ önbaxışındakı “JPEG yüklə” keçidi ilə görüntünü yükləyin, ChatGPT mesajına ayrıca əlavə edin və sonra tapşırığı göndərin. Yalnız fayl adının və ya tapşırığın yapışdırılması görüntünü ötürmür.</p>
<h2>Telefon, planşet və əlavəsiz brauzer</h2><p>JPEG önbaxışını yükləyib birbaşa ChatGPT mesajına əlavə edin. Bütün görüntüləri saxlamaq üçün ZIP də yüklənə bilər. “Tapşırığı kopyala” hazır mətni verir. Birbaşa JPEG üçün ZIP seçimini söndürün.</p>
<p>Əlavə ChatGPT interfeysi dəyişəndə yükləməni təsdiqləyə bilməzsə xəta göstərir. Yerli ZIP həddi 480 MB-dır; ChatGPT hesabının qəbul etdiyi fayl ölçüsü və sayı ayrıca tətbiq olunur. ChatGPT-nin görüntüyə faktiki baxdığını yalnız cavabdan yoxlamaq olar.</p>
<p>Yalnız seçilmiş görüntülər ötürülür. Nəticə radioloqun yoxlaması üçün layihədir. <a href="https://learn.chatgpt.com/docs/image-inputs" target="_blank" rel="noreferrer">OpenAI: görüntü əlavəetmə qaydası</a></p><a href="/report">Hesabata qayıt</a></main>}
